//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------
namespace consultaReinfPreWSDL
{
    using System;
    using System.ComponentModel;
    using System.Diagnostics;
    using System.Web.Services;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;

    // 
    // This source code was auto-generated by wsdl, Version=4.8.3928.0.
    // 


    /// <remarks/>
    // CODEGEN: O elemento de extensão WSDL opcional 'PolicyReference' do espaço para nome 'http://schemas.xmlsoap.org/ws/2004/09/policy' não foi tratado.
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name = "BasicHttpBinding_ConsultasReinf", Namespace = "http://sped.fazenda.gov.br/")]
    public partial class ConsultasReinf : System.Web.Services.Protocols.SoapHttpClientProtocol
    {

        private System.Threading.SendOrPostCallback ConsultaResultadoFechamento2099OperationCompleted;

        private System.Threading.SendOrPostCallback ConsultaInformacoesConsolidadasOperationCompleted;

        private System.Threading.SendOrPostCallback ConsultaReciboEvento1000OperationCompleted;

        private System.Threading.SendOrPostCallback ConsultaReciboEvento1070OperationCompleted;

        private System.Threading.SendOrPostCallback ConsultaReciboEvento2010OperationCompleted;

        private System.Threading.SendOrPostCallback ConsultaReciboEvento2020OperationCompleted;

        private System.Threading.SendOrPostCallback ConsultaReciboEvento2030OperationCompleted;

        private System.Threading.SendOrPostCallback ConsultaReciboEvento2040OperationCompleted;

        private System.Threading.SendOrPostCallback ConsultaReciboEvento2050OperationCompleted;

        private System.Threading.SendOrPostCallback ConsultaReciboEvento2055OperationCompleted;

        private System.Threading.SendOrPostCallback ConsultaReciboEvento2060OperationCompleted;

        private System.Threading.SendOrPostCallback ConsultaReciboEvento2098OperationCompleted;

        private System.Threading.SendOrPostCallback ConsultaReciboEvento2099OperationCompleted;

        private System.Threading.SendOrPostCallback ConsultaReciboEvento3010OperationCompleted;

        /// <remarks/>
        public ConsultasReinf()
        {
            this.Url = "https://reinf.receita.fazenda.gov.br/WsREINFConsultas/ConsultasReinf.svc";
        }

        /// <remarks/>
        public event ConsultaResultadoFechamento2099CompletedEventHandler ConsultaResultadoFechamento2099Completed;

        /// <remarks/>
        public event ConsultaInformacoesConsolidadasCompletedEventHandler ConsultaInformacoesConsolidadasCompleted;

        /// <remarks/>
        public event ConsultaReciboEvento1000CompletedEventHandler ConsultaReciboEvento1000Completed;

        /// <remarks/>
        public event ConsultaReciboEvento1070CompletedEventHandler ConsultaReciboEvento1070Completed;

        /// <remarks/>
        public event ConsultaReciboEvento2010CompletedEventHandler ConsultaReciboEvento2010Completed;

        /// <remarks/>
        public event ConsultaReciboEvento2020CompletedEventHandler ConsultaReciboEvento2020Completed;

        /// <remarks/>
        public event ConsultaReciboEvento2030CompletedEventHandler ConsultaReciboEvento2030Completed;

        /// <remarks/>
        public event ConsultaReciboEvento2040CompletedEventHandler ConsultaReciboEvento2040Completed;

        /// <remarks/>
        public event ConsultaReciboEvento2050CompletedEventHandler ConsultaReciboEvento2050Completed;

        /// <remarks/>
        public event ConsultaReciboEvento2055CompletedEventHandler ConsultaReciboEvento2055Completed;

        /// <remarks/>
        public event ConsultaReciboEvento2060CompletedEventHandler ConsultaReciboEvento2060Completed;

        /// <remarks/>
        public event ConsultaReciboEvento2098CompletedEventHandler ConsultaReciboEvento2098Completed;

        /// <remarks/>
        public event ConsultaReciboEvento2099CompletedEventHandler ConsultaReciboEvento2099Completed;

        /// <remarks/>
        public event ConsultaReciboEvento3010CompletedEventHandler ConsultaReciboEvento3010Completed;

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://sped.fazenda.gov.br/ConsultasReinf/ConsultaResultadoFechamento2099", RequestNamespace = "http://sped.fazenda.gov.br/", ResponseNamespace = "http://sped.fazenda.gov.br/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Xml.XmlNode ConsultaResultadoFechamento2099(byte tpInsc, string nrInsc, string numeroProtocoloFechamento)
        {
            object[] results = this.Invoke("ConsultaResultadoFechamento2099", new object[] {
                    tpInsc,
                    nrInsc,
                    numeroProtocoloFechamento});
            return ((System.Xml.XmlNode)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginConsultaResultadoFechamento2099(byte tpInsc, string nrInsc, string numeroProtocoloFechamento, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("ConsultaResultadoFechamento2099", new object[] {
                    tpInsc,
                    nrInsc,
                    numeroProtocoloFechamento}, callback, asyncState);
        }

        /// <remarks/>
        public System.Xml.XmlNode EndConsultaResultadoFechamento2099(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((System.Xml.XmlNode)(results[0]));
        }

        /// <remarks/>
        public void ConsultaResultadoFechamento2099Async(byte tpInsc, string nrInsc, string numeroProtocoloFechamento)
        {
            this.ConsultaResultadoFechamento2099Async(tpInsc, nrInsc, numeroProtocoloFechamento, null);
        }

        /// <remarks/>
        public void ConsultaResultadoFechamento2099Async(byte tpInsc, string nrInsc, string numeroProtocoloFechamento, object userState)
        {
            if ((this.ConsultaResultadoFechamento2099OperationCompleted == null))
            {
                this.ConsultaResultadoFechamento2099OperationCompleted = new System.Threading.SendOrPostCallback(this.OnConsultaResultadoFechamento2099OperationCompleted);
            }
            this.InvokeAsync("ConsultaResultadoFechamento2099", new object[] {
                    tpInsc,
                    nrInsc,
                    numeroProtocoloFechamento}, this.ConsultaResultadoFechamento2099OperationCompleted, userState);
        }

        private void OnConsultaResultadoFechamento2099OperationCompleted(object arg)
        {
            if ((this.ConsultaResultadoFechamento2099Completed != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ConsultaResultadoFechamento2099Completed(this, new ConsultaResultadoFechamento2099CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://sped.fazenda.gov.br/ConsultasReinf/ConsultaInformacoesConsolidadas", RequestNamespace = "http://sped.fazenda.gov.br/", ResponseNamespace = "http://sped.fazenda.gov.br/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Xml.XmlNode ConsultaInformacoesConsolidadas(byte tipoInscricaoContribuinte, string numeroInscricaoContribuinte, string numeroProtocoloFechamento)
        {
            object[] results = this.Invoke("ConsultaInformacoesConsolidadas", new object[] {
                    tipoInscricaoContribuinte,
                    numeroInscricaoContribuinte,
                    numeroProtocoloFechamento});
            return ((System.Xml.XmlNode)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginConsultaInformacoesConsolidadas(byte tipoInscricaoContribuinte, string numeroInscricaoContribuinte, string numeroProtocoloFechamento, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("ConsultaInformacoesConsolidadas", new object[] {
                    tipoInscricaoContribuinte,
                    numeroInscricaoContribuinte,
                    numeroProtocoloFechamento}, callback, asyncState);
        }

        /// <remarks/>
        public System.Xml.XmlNode EndConsultaInformacoesConsolidadas(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((System.Xml.XmlNode)(results[0]));
        }

        /// <remarks/>
        public void ConsultaInformacoesConsolidadasAsync(byte tipoInscricaoContribuinte, string numeroInscricaoContribuinte, string numeroProtocoloFechamento)
        {
            this.ConsultaInformacoesConsolidadasAsync(tipoInscricaoContribuinte, numeroInscricaoContribuinte, numeroProtocoloFechamento, null);
        }

        /// <remarks/>
        public void ConsultaInformacoesConsolidadasAsync(byte tipoInscricaoContribuinte, string numeroInscricaoContribuinte, string numeroProtocoloFechamento, object userState)
        {
            if ((this.ConsultaInformacoesConsolidadasOperationCompleted == null))
            {
                this.ConsultaInformacoesConsolidadasOperationCompleted = new System.Threading.SendOrPostCallback(this.OnConsultaInformacoesConsolidadasOperationCompleted);
            }
            this.InvokeAsync("ConsultaInformacoesConsolidadas", new object[] {
                    tipoInscricaoContribuinte,
                    numeroInscricaoContribuinte,
                    numeroProtocoloFechamento}, this.ConsultaInformacoesConsolidadasOperationCompleted, userState);
        }

        private void OnConsultaInformacoesConsolidadasOperationCompleted(object arg)
        {
            if ((this.ConsultaInformacoesConsolidadasCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ConsultaInformacoesConsolidadasCompleted(this, new ConsultaInformacoesConsolidadasCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://sped.fazenda.gov.br/ConsultasReinf/ConsultaReciboEvento1000", RequestNamespace = "http://sped.fazenda.gov.br/", ResponseNamespace = "http://sped.fazenda.gov.br/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Xml.XmlNode ConsultaReciboEvento1000(int tipoEvento, byte tpInsc, string nrInsc)
        {
            object[] results = this.Invoke("ConsultaReciboEvento1000", new object[] {
                    tipoEvento,
                    tpInsc,
                    nrInsc});
            return ((System.Xml.XmlNode)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginConsultaReciboEvento1000(int tipoEvento, byte tpInsc, string nrInsc, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("ConsultaReciboEvento1000", new object[] {
                    tipoEvento,
                    tpInsc,
                    nrInsc}, callback, asyncState);
        }

        /// <remarks/>
        public System.Xml.XmlNode EndConsultaReciboEvento1000(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((System.Xml.XmlNode)(results[0]));
        }

        /// <remarks/>
        public void ConsultaReciboEvento1000Async(int tipoEvento, byte tpInsc, string nrInsc)
        {
            this.ConsultaReciboEvento1000Async(tipoEvento, tpInsc, nrInsc, null);
        }

        /// <remarks/>
        public void ConsultaReciboEvento1000Async(int tipoEvento, byte tpInsc, string nrInsc, object userState)
        {
            if ((this.ConsultaReciboEvento1000OperationCompleted == null))
            {
                this.ConsultaReciboEvento1000OperationCompleted = new System.Threading.SendOrPostCallback(this.OnConsultaReciboEvento1000OperationCompleted);
            }
            this.InvokeAsync("ConsultaReciboEvento1000", new object[] {
                    tipoEvento,
                    tpInsc,
                    nrInsc}, this.ConsultaReciboEvento1000OperationCompleted, userState);
        }

        private void OnConsultaReciboEvento1000OperationCompleted(object arg)
        {
            if ((this.ConsultaReciboEvento1000Completed != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ConsultaReciboEvento1000Completed(this, new ConsultaReciboEvento1000CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://sped.fazenda.gov.br/ConsultasReinf/ConsultaReciboEvento1070", RequestNamespace = "http://sped.fazenda.gov.br/", ResponseNamespace = "http://sped.fazenda.gov.br/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Xml.XmlNode ConsultaReciboEvento1070(int tipoEvento, byte tpInsc, string nrInsc)
        {
            object[] results = this.Invoke("ConsultaReciboEvento1070", new object[] {
                    tipoEvento,
                    tpInsc,
                    nrInsc});
            return ((System.Xml.XmlNode)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginConsultaReciboEvento1070(int tipoEvento, byte tpInsc, string nrInsc, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("ConsultaReciboEvento1070", new object[] {
                    tipoEvento,
                    tpInsc,
                    nrInsc}, callback, asyncState);
        }

        /// <remarks/>
        public System.Xml.XmlNode EndConsultaReciboEvento1070(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((System.Xml.XmlNode)(results[0]));
        }

        /// <remarks/>
        public void ConsultaReciboEvento1070Async(int tipoEvento, byte tpInsc, string nrInsc)
        {
            this.ConsultaReciboEvento1070Async(tipoEvento, tpInsc, nrInsc, null);
        }

        /// <remarks/>
        public void ConsultaReciboEvento1070Async(int tipoEvento, byte tpInsc, string nrInsc, object userState)
        {
            if ((this.ConsultaReciboEvento1070OperationCompleted == null))
            {
                this.ConsultaReciboEvento1070OperationCompleted = new System.Threading.SendOrPostCallback(this.OnConsultaReciboEvento1070OperationCompleted);
            }
            this.InvokeAsync("ConsultaReciboEvento1070", new object[] {
                    tipoEvento,
                    tpInsc,
                    nrInsc}, this.ConsultaReciboEvento1070OperationCompleted, userState);
        }

        private void OnConsultaReciboEvento1070OperationCompleted(object arg)
        {
            if ((this.ConsultaReciboEvento1070Completed != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ConsultaReciboEvento1070Completed(this, new ConsultaReciboEvento1070CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://sped.fazenda.gov.br/ConsultasReinf/ConsultaReciboEvento2010", RequestNamespace = "http://sped.fazenda.gov.br/", ResponseNamespace = "http://sped.fazenda.gov.br/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Xml.XmlNode ConsultaReciboEvento2010(int tipoEvento, byte tpInsc, string nrInsc, string perApur, byte tpInscEstab, string nrInscEstab, string cnpjPrestador)
        {
            object[] results = this.Invoke("ConsultaReciboEvento2010", new object[] {
                    tipoEvento,
                    tpInsc,
                    nrInsc,
                    perApur,
                    tpInscEstab,
                    nrInscEstab,
                    cnpjPrestador});
            return ((System.Xml.XmlNode)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginConsultaReciboEvento2010(int tipoEvento, byte tpInsc, string nrInsc, string perApur, byte tpInscEstab, string nrInscEstab, string cnpjPrestador, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("ConsultaReciboEvento2010", new object[] {
                    tipoEvento,
                    tpInsc,
                    nrInsc,
                    perApur,
                    tpInscEstab,
                    nrInscEstab,
                    cnpjPrestador}, callback, asyncState);
        }

        /// <remarks/>
        public System.Xml.XmlNode EndConsultaReciboEvento2010(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((System.Xml.XmlNode)(results[0]));
        }

        /// <remarks/>
        public void ConsultaReciboEvento2010Async(int tipoEvento, byte tpInsc, string nrInsc, string perApur, byte tpInscEstab, string nrInscEstab, string cnpjPrestador)
        {
            this.ConsultaReciboEvento2010Async(tipoEvento, tpInsc, nrInsc, perApur, tpInscEstab, nrInscEstab, cnpjPrestador, null);
        }

        /// <remarks/>
        public void ConsultaReciboEvento2010Async(int tipoEvento, byte tpInsc, string nrInsc, string perApur, byte tpInscEstab, string nrInscEstab, string cnpjPrestador, object userState)
        {
            if ((this.ConsultaReciboEvento2010OperationCompleted == null))
            {
                this.ConsultaReciboEvento2010OperationCompleted = new System.Threading.SendOrPostCallback(this.OnConsultaReciboEvento2010OperationCompleted);
            }
            this.InvokeAsync("ConsultaReciboEvento2010", new object[] {
                    tipoEvento,
                    tpInsc,
                    nrInsc,
                    perApur,
                    tpInscEstab,
                    nrInscEstab,
                    cnpjPrestador}, this.ConsultaReciboEvento2010OperationCompleted, userState);
        }

        private void OnConsultaReciboEvento2010OperationCompleted(object arg)
        {
            if ((this.ConsultaReciboEvento2010Completed != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ConsultaReciboEvento2010Completed(this, new ConsultaReciboEvento2010CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://sped.fazenda.gov.br/ConsultasReinf/ConsultaReciboEvento2020", RequestNamespace = "http://sped.fazenda.gov.br/", ResponseNamespace = "http://sped.fazenda.gov.br/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Xml.XmlNode ConsultaReciboEvento2020(int tipoEvento, byte tpInsc, string nrInsc, string perApur, string nrInscEstabPrest, byte tpInscTomador, string nrInscTomador)
        {
            object[] results = this.Invoke("ConsultaReciboEvento2020", new object[] {
                    tipoEvento,
                    tpInsc,
                    nrInsc,
                    perApur,
                    nrInscEstabPrest,
                    tpInscTomador,
                    nrInscTomador});
            return ((System.Xml.XmlNode)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginConsultaReciboEvento2020(int tipoEvento, byte tpInsc, string nrInsc, string perApur, string nrInscEstabPrest, byte tpInscTomador, string nrInscTomador, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("ConsultaReciboEvento2020", new object[] {
                    tipoEvento,
                    tpInsc,
                    nrInsc,
                    perApur,
                    nrInscEstabPrest,
                    tpInscTomador,
                    nrInscTomador}, callback, asyncState);
        }

        /// <remarks/>
        public System.Xml.XmlNode EndConsultaReciboEvento2020(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((System.Xml.XmlNode)(results[0]));
        }

        /// <remarks/>
        public void ConsultaReciboEvento2020Async(int tipoEvento, byte tpInsc, string nrInsc, string perApur, string nrInscEstabPrest, byte tpInscTomador, string nrInscTomador)
        {
            this.ConsultaReciboEvento2020Async(tipoEvento, tpInsc, nrInsc, perApur, nrInscEstabPrest, tpInscTomador, nrInscTomador, null);
        }

        /// <remarks/>
        public void ConsultaReciboEvento2020Async(int tipoEvento, byte tpInsc, string nrInsc, string perApur, string nrInscEstabPrest, byte tpInscTomador, string nrInscTomador, object userState)
        {
            if ((this.ConsultaReciboEvento2020OperationCompleted == null))
            {
                this.ConsultaReciboEvento2020OperationCompleted = new System.Threading.SendOrPostCallback(this.OnConsultaReciboEvento2020OperationCompleted);
            }
            this.InvokeAsync("ConsultaReciboEvento2020", new object[] {
                    tipoEvento,
                    tpInsc,
                    nrInsc,
                    perApur,
                    nrInscEstabPrest,
                    tpInscTomador,
                    nrInscTomador}, this.ConsultaReciboEvento2020OperationCompleted, userState);
        }

        private void OnConsultaReciboEvento2020OperationCompleted(object arg)
        {
            if ((this.ConsultaReciboEvento2020Completed != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ConsultaReciboEvento2020Completed(this, new ConsultaReciboEvento2020CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://sped.fazenda.gov.br/ConsultasReinf/ConsultaReciboEvento2030", RequestNamespace = "http://sped.fazenda.gov.br/", ResponseNamespace = "http://sped.fazenda.gov.br/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Xml.XmlNode ConsultaReciboEvento2030(int tipoEvento, byte tpInsc, string nrInsc, string perApur, string nrInscEstab)
        {
            object[] results = this.Invoke("ConsultaReciboEvento2030", new object[] {
                    tipoEvento,
                    tpInsc,
                    nrInsc,
                    perApur,
                    nrInscEstab});
            return ((System.Xml.XmlNode)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginConsultaReciboEvento2030(int tipoEvento, byte tpInsc, string nrInsc, string perApur, string nrInscEstab, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("ConsultaReciboEvento2030", new object[] {
                    tipoEvento,
                    tpInsc,
                    nrInsc,
                    perApur,
                    nrInscEstab}, callback, asyncState);
        }

        /// <remarks/>
        public System.Xml.XmlNode EndConsultaReciboEvento2030(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((System.Xml.XmlNode)(results[0]));
        }

        /// <remarks/>
        public void ConsultaReciboEvento2030Async(int tipoEvento, byte tpInsc, string nrInsc, string perApur, string nrInscEstab)
        {
            this.ConsultaReciboEvento2030Async(tipoEvento, tpInsc, nrInsc, perApur, nrInscEstab, null);
        }

        /// <remarks/>
        public void ConsultaReciboEvento2030Async(int tipoEvento, byte tpInsc, string nrInsc, string perApur, string nrInscEstab, object userState)
        {
            if ((this.ConsultaReciboEvento2030OperationCompleted == null))
            {
                this.ConsultaReciboEvento2030OperationCompleted = new System.Threading.SendOrPostCallback(this.OnConsultaReciboEvento2030OperationCompleted);
            }
            this.InvokeAsync("ConsultaReciboEvento2030", new object[] {
                    tipoEvento,
                    tpInsc,
                    nrInsc,
                    perApur,
                    nrInscEstab}, this.ConsultaReciboEvento2030OperationCompleted, userState);
        }

        private void OnConsultaReciboEvento2030OperationCompleted(object arg)
        {
            if ((this.ConsultaReciboEvento2030Completed != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ConsultaReciboEvento2030Completed(this, new ConsultaReciboEvento2030CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://sped.fazenda.gov.br/ConsultasReinf/ConsultaReciboEvento2040", RequestNamespace = "http://sped.fazenda.gov.br/", ResponseNamespace = "http://sped.fazenda.gov.br/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Xml.XmlNode ConsultaReciboEvento2040(int tipoEvento, byte tpInsc, string nrInsc, string perApur, string nrInscEstab)
        {
            object[] results = this.Invoke("ConsultaReciboEvento2040", new object[] {
                    tipoEvento,
                    tpInsc,
                    nrInsc,
                    perApur,
                    nrInscEstab});
            return ((System.Xml.XmlNode)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginConsultaReciboEvento2040(int tipoEvento, byte tpInsc, string nrInsc, string perApur, string nrInscEstab, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("ConsultaReciboEvento2040", new object[] {
                    tipoEvento,
                    tpInsc,
                    nrInsc,
                    perApur,
                    nrInscEstab}, callback, asyncState);
        }

        /// <remarks/>
        public System.Xml.XmlNode EndConsultaReciboEvento2040(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((System.Xml.XmlNode)(results[0]));
        }

        /// <remarks/>
        public void ConsultaReciboEvento2040Async(int tipoEvento, byte tpInsc, string nrInsc, string perApur, string nrInscEstab)
        {
            this.ConsultaReciboEvento2040Async(tipoEvento, tpInsc, nrInsc, perApur, nrInscEstab, null);
        }

        /// <remarks/>
        public void ConsultaReciboEvento2040Async(int tipoEvento, byte tpInsc, string nrInsc, string perApur, string nrInscEstab, object userState)
        {
            if ((this.ConsultaReciboEvento2040OperationCompleted == null))
            {
                this.ConsultaReciboEvento2040OperationCompleted = new System.Threading.SendOrPostCallback(this.OnConsultaReciboEvento2040OperationCompleted);
            }
            this.InvokeAsync("ConsultaReciboEvento2040", new object[] {
                    tipoEvento,
                    tpInsc,
                    nrInsc,
                    perApur,
                    nrInscEstab}, this.ConsultaReciboEvento2040OperationCompleted, userState);
        }

        private void OnConsultaReciboEvento2040OperationCompleted(object arg)
        {
            if ((this.ConsultaReciboEvento2040Completed != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ConsultaReciboEvento2040Completed(this, new ConsultaReciboEvento2040CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://sped.fazenda.gov.br/ConsultasReinf/ConsultaReciboEvento2050", RequestNamespace = "http://sped.fazenda.gov.br/", ResponseNamespace = "http://sped.fazenda.gov.br/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Xml.XmlNode ConsultaReciboEvento2050(int tipoEvento, byte tpInsc, string nrInsc, string perApur, string nrInscEstab)
        {
            object[] results = this.Invoke("ConsultaReciboEvento2050", new object[] {
                    tipoEvento,
                    tpInsc,
                    nrInsc,
                    perApur,
                    nrInscEstab});
            return ((System.Xml.XmlNode)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginConsultaReciboEvento2050(int tipoEvento, byte tpInsc, string nrInsc, string perApur, string nrInscEstab, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("ConsultaReciboEvento2050", new object[] {
                    tipoEvento,
                    tpInsc,
                    nrInsc,
                    perApur,
                    nrInscEstab}, callback, asyncState);
        }

        /// <remarks/>
        public System.Xml.XmlNode EndConsultaReciboEvento2050(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((System.Xml.XmlNode)(results[0]));
        }

        /// <remarks/>
        public void ConsultaReciboEvento2050Async(int tipoEvento, byte tpInsc, string nrInsc, string perApur, string nrInscEstab)
        {
            this.ConsultaReciboEvento2050Async(tipoEvento, tpInsc, nrInsc, perApur, nrInscEstab, null);
        }

        /// <remarks/>
        public void ConsultaReciboEvento2050Async(int tipoEvento, byte tpInsc, string nrInsc, string perApur, string nrInscEstab, object userState)
        {
            if ((this.ConsultaReciboEvento2050OperationCompleted == null))
            {
                this.ConsultaReciboEvento2050OperationCompleted = new System.Threading.SendOrPostCallback(this.OnConsultaReciboEvento2050OperationCompleted);
            }
            this.InvokeAsync("ConsultaReciboEvento2050", new object[] {
                    tipoEvento,
                    tpInsc,
                    nrInsc,
                    perApur,
                    nrInscEstab}, this.ConsultaReciboEvento2050OperationCompleted, userState);
        }

        private void OnConsultaReciboEvento2050OperationCompleted(object arg)
        {
            if ((this.ConsultaReciboEvento2050Completed != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ConsultaReciboEvento2050Completed(this, new ConsultaReciboEvento2050CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://sped.fazenda.gov.br/ConsultasReinf/ConsultaReciboEvento2055", RequestNamespace = "http://sped.fazenda.gov.br/", ResponseNamespace = "http://sped.fazenda.gov.br/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Xml.XmlNode ConsultaReciboEvento2055(int tipoEvento, byte tpInsc, string nrInsc, string perApur, byte tpInscAdq, string nrInscAdq, byte tpInscProd, string nrInscProd)
        {
            object[] results = this.Invoke("ConsultaReciboEvento2055", new object[] {
                    tipoEvento,
                    tpInsc,
                    nrInsc,
                    perApur,
                    tpInscAdq,
                    nrInscAdq,
                    tpInscProd,
                    nrInscProd});
            return ((System.Xml.XmlNode)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginConsultaReciboEvento2055(int tipoEvento, byte tpInsc, string nrInsc, string perApur, byte tpInscAdq, string nrInscAdq, byte tpInscProd, string nrInscProd, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("ConsultaReciboEvento2055", new object[] {
                    tipoEvento,
                    tpInsc,
                    nrInsc,
                    perApur,
                    tpInscAdq,
                    nrInscAdq,
                    tpInscProd,
                    nrInscProd}, callback, asyncState);
        }

        /// <remarks/>
        public System.Xml.XmlNode EndConsultaReciboEvento2055(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((System.Xml.XmlNode)(results[0]));
        }

        /// <remarks/>
        public void ConsultaReciboEvento2055Async(int tipoEvento, byte tpInsc, string nrInsc, string perApur, byte tpInscAdq, string nrInscAdq, byte tpInscProd, string nrInscProd)
        {
            this.ConsultaReciboEvento2055Async(tipoEvento, tpInsc, nrInsc, perApur, tpInscAdq, nrInscAdq, tpInscProd, nrInscProd, null);
        }

        /// <remarks/>
        public void ConsultaReciboEvento2055Async(int tipoEvento, byte tpInsc, string nrInsc, string perApur, byte tpInscAdq, string nrInscAdq, byte tpInscProd, string nrInscProd, object userState)
        {
            if ((this.ConsultaReciboEvento2055OperationCompleted == null))
            {
                this.ConsultaReciboEvento2055OperationCompleted = new System.Threading.SendOrPostCallback(this.OnConsultaReciboEvento2055OperationCompleted);
            }
            this.InvokeAsync("ConsultaReciboEvento2055", new object[] {
                    tipoEvento,
                    tpInsc,
                    nrInsc,
                    perApur,
                    tpInscAdq,
                    nrInscAdq,
                    tpInscProd,
                    nrInscProd}, this.ConsultaReciboEvento2055OperationCompleted, userState);
        }

        private void OnConsultaReciboEvento2055OperationCompleted(object arg)
        {
            if ((this.ConsultaReciboEvento2055Completed != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ConsultaReciboEvento2055Completed(this, new ConsultaReciboEvento2055CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://sped.fazenda.gov.br/ConsultasReinf/ConsultaReciboEvento2060", RequestNamespace = "http://sped.fazenda.gov.br/", ResponseNamespace = "http://sped.fazenda.gov.br/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Xml.XmlNode ConsultaReciboEvento2060(int tipoEvento, byte tpInsc, string nrInsc, string perApur, byte tpInscEstab, string nrInscEstab)
        {
            object[] results = this.Invoke("ConsultaReciboEvento2060", new object[] {
                    tipoEvento,
                    tpInsc,
                    nrInsc,
                    perApur,
                    tpInscEstab,
                    nrInscEstab});
            return ((System.Xml.XmlNode)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginConsultaReciboEvento2060(int tipoEvento, byte tpInsc, string nrInsc, string perApur, byte tpInscEstab, string nrInscEstab, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("ConsultaReciboEvento2060", new object[] {
                    tipoEvento,
                    tpInsc,
                    nrInsc,
                    perApur,
                    tpInscEstab,
                    nrInscEstab}, callback, asyncState);
        }

        /// <remarks/>
        public System.Xml.XmlNode EndConsultaReciboEvento2060(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((System.Xml.XmlNode)(results[0]));
        }

        /// <remarks/>
        public void ConsultaReciboEvento2060Async(int tipoEvento, byte tpInsc, string nrInsc, string perApur, byte tpInscEstab, string nrInscEstab)
        {
            this.ConsultaReciboEvento2060Async(tipoEvento, tpInsc, nrInsc, perApur, tpInscEstab, nrInscEstab, null);
        }

        /// <remarks/>
        public void ConsultaReciboEvento2060Async(int tipoEvento, byte tpInsc, string nrInsc, string perApur, byte tpInscEstab, string nrInscEstab, object userState)
        {
            if ((this.ConsultaReciboEvento2060OperationCompleted == null))
            {
                this.ConsultaReciboEvento2060OperationCompleted = new System.Threading.SendOrPostCallback(this.OnConsultaReciboEvento2060OperationCompleted);
            }
            this.InvokeAsync("ConsultaReciboEvento2060", new object[] {
                    tipoEvento,
                    tpInsc,
                    nrInsc,
                    perApur,
                    tpInscEstab,
                    nrInscEstab}, this.ConsultaReciboEvento2060OperationCompleted, userState);
        }

        private void OnConsultaReciboEvento2060OperationCompleted(object arg)
        {
            if ((this.ConsultaReciboEvento2060Completed != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ConsultaReciboEvento2060Completed(this, new ConsultaReciboEvento2060CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://sped.fazenda.gov.br/ConsultasReinf/ConsultaReciboEvento2098", RequestNamespace = "http://sped.fazenda.gov.br/", ResponseNamespace = "http://sped.fazenda.gov.br/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Xml.XmlNode ConsultaReciboEvento2098(int tipoEvento, byte tpInsc, string nrInsc, string perApur)
        {
            object[] results = this.Invoke("ConsultaReciboEvento2098", new object[] {
                    tipoEvento,
                    tpInsc,
                    nrInsc,
                    perApur});
            return ((System.Xml.XmlNode)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginConsultaReciboEvento2098(int tipoEvento, byte tpInsc, string nrInsc, string perApur, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("ConsultaReciboEvento2098", new object[] {
                    tipoEvento,
                    tpInsc,
                    nrInsc,
                    perApur}, callback, asyncState);
        }

        /// <remarks/>
        public System.Xml.XmlNode EndConsultaReciboEvento2098(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((System.Xml.XmlNode)(results[0]));
        }

        /// <remarks/>
        public void ConsultaReciboEvento2098Async(int tipoEvento, byte tpInsc, string nrInsc, string perApur)
        {
            this.ConsultaReciboEvento2098Async(tipoEvento, tpInsc, nrInsc, perApur, null);
        }

        /// <remarks/>
        public void ConsultaReciboEvento2098Async(int tipoEvento, byte tpInsc, string nrInsc, string perApur, object userState)
        {
            if ((this.ConsultaReciboEvento2098OperationCompleted == null))
            {
                this.ConsultaReciboEvento2098OperationCompleted = new System.Threading.SendOrPostCallback(this.OnConsultaReciboEvento2098OperationCompleted);
            }
            this.InvokeAsync("ConsultaReciboEvento2098", new object[] {
                    tipoEvento,
                    tpInsc,
                    nrInsc,
                    perApur}, this.ConsultaReciboEvento2098OperationCompleted, userState);
        }

        private void OnConsultaReciboEvento2098OperationCompleted(object arg)
        {
            if ((this.ConsultaReciboEvento2098Completed != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ConsultaReciboEvento2098Completed(this, new ConsultaReciboEvento2098CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://sped.fazenda.gov.br/ConsultasReinf/ConsultaReciboEvento2099", RequestNamespace = "http://sped.fazenda.gov.br/", ResponseNamespace = "http://sped.fazenda.gov.br/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Xml.XmlNode ConsultaReciboEvento2099(int tipoEvento, byte tpInsc, string nrInsc, string perApur)
        {
            object[] results = this.Invoke("ConsultaReciboEvento2099", new object[] {
                    tipoEvento,
                    tpInsc,
                    nrInsc,
                    perApur});
            return ((System.Xml.XmlNode)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginConsultaReciboEvento2099(int tipoEvento, byte tpInsc, string nrInsc, string perApur, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("ConsultaReciboEvento2099", new object[] {
                    tipoEvento,
                    tpInsc,
                    nrInsc,
                    perApur}, callback, asyncState);
        }

        /// <remarks/>
        public System.Xml.XmlNode EndConsultaReciboEvento2099(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((System.Xml.XmlNode)(results[0]));
        }

        /// <remarks/>
        public void ConsultaReciboEvento2099Async(int tipoEvento, byte tpInsc, string nrInsc, string perApur)
        {
            this.ConsultaReciboEvento2099Async(tipoEvento, tpInsc, nrInsc, perApur, null);
        }

        /// <remarks/>
        public void ConsultaReciboEvento2099Async(int tipoEvento, byte tpInsc, string nrInsc, string perApur, object userState)
        {
            if ((this.ConsultaReciboEvento2099OperationCompleted == null))
            {
                this.ConsultaReciboEvento2099OperationCompleted = new System.Threading.SendOrPostCallback(this.OnConsultaReciboEvento2099OperationCompleted);
            }
            this.InvokeAsync("ConsultaReciboEvento2099", new object[] {
                    tipoEvento,
                    tpInsc,
                    nrInsc,
                    perApur}, this.ConsultaReciboEvento2099OperationCompleted, userState);
        }

        private void OnConsultaReciboEvento2099OperationCompleted(object arg)
        {
            if ((this.ConsultaReciboEvento2099Completed != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ConsultaReciboEvento2099Completed(this, new ConsultaReciboEvento2099CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://sped.fazenda.gov.br/ConsultasReinf/ConsultaReciboEvento3010", RequestNamespace = "http://sped.fazenda.gov.br/", ResponseNamespace = "http://sped.fazenda.gov.br/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Xml.XmlNode ConsultaReciboEvento3010(int tipoEvento, byte tpInsc, string nrInsc, string dtApur, string nrInscEstabelecimento)
        {
            object[] results = this.Invoke("ConsultaReciboEvento3010", new object[] {
                    tipoEvento,
                    tpInsc,
                    nrInsc,
                    dtApur,
                    nrInscEstabelecimento});
            return ((System.Xml.XmlNode)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginConsultaReciboEvento3010(int tipoEvento, byte tpInsc, string nrInsc, string dtApur, string nrInscEstabelecimento, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("ConsultaReciboEvento3010", new object[] {
                    tipoEvento,
                    tpInsc,
                    nrInsc,
                    dtApur,
                    nrInscEstabelecimento}, callback, asyncState);
        }

        /// <remarks/>
        public System.Xml.XmlNode EndConsultaReciboEvento3010(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((System.Xml.XmlNode)(results[0]));
        }

        /// <remarks/>
        public void ConsultaReciboEvento3010Async(int tipoEvento, byte tpInsc, string nrInsc, string dtApur, string nrInscEstabelecimento)
        {
            this.ConsultaReciboEvento3010Async(tipoEvento, tpInsc, nrInsc, dtApur, nrInscEstabelecimento, null);
        }

        /// <remarks/>
        public void ConsultaReciboEvento3010Async(int tipoEvento, byte tpInsc, string nrInsc, string dtApur, string nrInscEstabelecimento, object userState)
        {
            if ((this.ConsultaReciboEvento3010OperationCompleted == null))
            {
                this.ConsultaReciboEvento3010OperationCompleted = new System.Threading.SendOrPostCallback(this.OnConsultaReciboEvento3010OperationCompleted);
            }
            this.InvokeAsync("ConsultaReciboEvento3010", new object[] {
                    tipoEvento,
                    tpInsc,
                    nrInsc,
                    dtApur,
                    nrInscEstabelecimento}, this.ConsultaReciboEvento3010OperationCompleted, userState);
        }

        private void OnConsultaReciboEvento3010OperationCompleted(object arg)
        {
            if ((this.ConsultaReciboEvento3010Completed != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ConsultaReciboEvento3010Completed(this, new ConsultaReciboEvento3010CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        public new void CancelAsync(object userState)
        {
            base.CancelAsync(userState);
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
    public delegate void ConsultaResultadoFechamento2099CompletedEventHandler(object sender, ConsultaResultadoFechamento2099CompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConsultaResultadoFechamento2099CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal ConsultaResultadoFechamento2099CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
                base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public System.Xml.XmlNode Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlNode)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
    public delegate void ConsultaInformacoesConsolidadasCompletedEventHandler(object sender, ConsultaInformacoesConsolidadasCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConsultaInformacoesConsolidadasCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal ConsultaInformacoesConsolidadasCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
                base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public System.Xml.XmlNode Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlNode)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
    public delegate void ConsultaReciboEvento1000CompletedEventHandler(object sender, ConsultaReciboEvento1000CompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConsultaReciboEvento1000CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal ConsultaReciboEvento1000CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
                base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public System.Xml.XmlNode Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlNode)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
    public delegate void ConsultaReciboEvento1070CompletedEventHandler(object sender, ConsultaReciboEvento1070CompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConsultaReciboEvento1070CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal ConsultaReciboEvento1070CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
                base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public System.Xml.XmlNode Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlNode)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
    public delegate void ConsultaReciboEvento2010CompletedEventHandler(object sender, ConsultaReciboEvento2010CompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConsultaReciboEvento2010CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal ConsultaReciboEvento2010CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
                base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public System.Xml.XmlNode Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlNode)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
    public delegate void ConsultaReciboEvento2020CompletedEventHandler(object sender, ConsultaReciboEvento2020CompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConsultaReciboEvento2020CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal ConsultaReciboEvento2020CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
                base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public System.Xml.XmlNode Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlNode)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
    public delegate void ConsultaReciboEvento2030CompletedEventHandler(object sender, ConsultaReciboEvento2030CompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConsultaReciboEvento2030CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal ConsultaReciboEvento2030CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
                base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public System.Xml.XmlNode Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlNode)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
    public delegate void ConsultaReciboEvento2040CompletedEventHandler(object sender, ConsultaReciboEvento2040CompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConsultaReciboEvento2040CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal ConsultaReciboEvento2040CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
                base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public System.Xml.XmlNode Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlNode)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
    public delegate void ConsultaReciboEvento2050CompletedEventHandler(object sender, ConsultaReciboEvento2050CompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConsultaReciboEvento2050CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal ConsultaReciboEvento2050CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
                base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public System.Xml.XmlNode Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlNode)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
    public delegate void ConsultaReciboEvento2055CompletedEventHandler(object sender, ConsultaReciboEvento2055CompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConsultaReciboEvento2055CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal ConsultaReciboEvento2055CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
                base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public System.Xml.XmlNode Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlNode)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
    public delegate void ConsultaReciboEvento2060CompletedEventHandler(object sender, ConsultaReciboEvento2060CompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConsultaReciboEvento2060CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal ConsultaReciboEvento2060CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
                base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public System.Xml.XmlNode Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlNode)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
    public delegate void ConsultaReciboEvento2098CompletedEventHandler(object sender, ConsultaReciboEvento2098CompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConsultaReciboEvento2098CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal ConsultaReciboEvento2098CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
                base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public System.Xml.XmlNode Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlNode)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
    public delegate void ConsultaReciboEvento2099CompletedEventHandler(object sender, ConsultaReciboEvento2099CompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConsultaReciboEvento2099CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal ConsultaReciboEvento2099CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
                base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public System.Xml.XmlNode Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlNode)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
    public delegate void ConsultaReciboEvento3010CompletedEventHandler(object sender, ConsultaReciboEvento3010CompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConsultaReciboEvento3010CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal ConsultaReciboEvento3010CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
                base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public System.Xml.XmlNode Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlNode)(this.results[0]));
            }
        }
    }
}